on: ["push", "pull_request"]

name: Coveralls

defaults:
  run:
    working-directory: client

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.1.2

    - name: Setup Node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.x

    - name: Install Deps and Get Coverage
      run: |
        npm install
        npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2.2.3
