name: 'Vitest Coverage'
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npx vitest --coverage.enabled
    - name: 'Report Coverage'
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2.3.0
      with:
        working-directory: ./client
    - name: Vitest Badge Action
      uses: wjervis7/vitest-badge-action@v1.0.0
      if: success() || failure()
      with:
        result-type: lines
        badge-path: ./client/coverage/badge.svg
        vitest-config-path: ./client/vitest.config.mjs
        badge-text: Coverage
        badge-pass-color: EBFFF5
        badge-fail-color: EF6F6C
        badge-neutral-color: 435049
        gist-token: ${{ secrets.GIST_TOKEN }}
        gist-url: https://gist.github.com/mayorofdesalle/trailtracer-coverage-badge.svg
        upload-badge: ${{ github.base_ref == 'refs/heads/main' }}
